# Generated by Django 6.0.6 on 2026-06-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_template',
            field=models.CharField(blank=True, choices=[('classic-scholar', 'Classic Scholar'), ('modern-dark', 'Modern Dark'), ('minimalist-lab', 'Minimalist Lab'), ('executive-academic', 'Executive Academic')], default='classic-scholar', max_length=50, null=True),
        ),
    ]
