# Generated by Django 6.0.6 on 2026-06-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_profile_selected_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='research_interests',
            field=models.TextField(blank=True, default=''),
        ),
    ]
